server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          jws-algorithms: HS256
          jws-algorithms: RS512
          jwk-set-uri: http://localhost:8180/realms/oauth2/protocol/openid-connect/certs

jwt:
  keyId: 4515037e-57f9-4d91-b0f7-666d55cfa008
    
